| Discrepancy Type | Count of rows | Percentage of Total Entries (Rounded) |
|------------------|---------------|---------------------------------------|
| Spelling | 21 | 7.17% |
| Punctuation | 14 | 4.78% |
| Wording | 44 | 15.02% |
| Numerical Difference | 32 | 10.92% |
| NO ERRORS | 23 | 7.85% |
| Content Mix-up | 79 | 26.96% |
| Missing Content | 11 | 3.75% |
| Extra Content | 19 | 6.48% |
| Capitalization | 0 | 0.0% |
| Omission | 17 | 5.8% |
