<sol_start id=7>

Respiration in plants

Respiration in animals

(i)

They do not breathe, they respire through their leaves.

(i)

They breathe air for respiration.

(ii)

Respiratory organs are absent. Respiration takes place through diffusion.

(ii)

Respiratory organs are present like lungs (in human), gills (in fishes) etc.

7.

<sol_end>