<sol_start id=8>

Light Reaction

Dark Reaction

(i)

It takes place in the grana part of the chloroplast.

(i)

It takes place in the stroma part of the chloroplast.

(ii)

It is a photochemical phase.

(ii)

It is a biochemical phase.

(iii)

The end products are ATP and NADPH.

(iii)

The end product is glucose.

8.
![alt text](image1.png)

<image1.png>

<sol_end>10. (a) Role of Hydrochloride acid in stomach :

(1) It kills the germs in the stomach.

(2) It creates an acidic medium for enzyme pepsin to actron protein activate.

<sub_id end>

<sub_id = 2>

(b) A drawing of a structure

AI-generated content may be incorrect.

Function of lacteal – During the process of digestion, the lacteals absorb large molecules of fats and lipids from the small intestine.

<sub_id end>A drawing of a structure

AI-generated content may be incorrect.
Function of lacteal – During the process of digestion, the lacteals absorb large molecules of fats and lipids from the small intestine.

<sub_id end>
<sub_id = 1>

17.(i)(a) Dendrites

(b) Axon

<sub_id end>

<sub_id = 2>

(ii) 

<sub_id end>

