| Discrepancy Type | Count of rows | Percentage of Total Entries (Rounded) |
|------------------|---------------|---------------------------------------|
| Spelling | 9 | 36.0% |
| Punctuation | 4 | 16.0% |
| Wording | 7 | 28.0% |
| Numerical Difference | 1 | 4.0% |
| NO ERRORS | 4 | 16.0% |
| Content Mix-up | 1 | 4.0% |
| Missing Content | 11 | 44.0% |
| Extra Content | 11 | 44.0% |
| Capitalization | 0 | 0.0% |
| Omission | 0 | 0.0% |
