---
title: OCR Comparison Table for 01_10021165141080491171694788750
---

| question number | Human_ocr | Gemini_ocr | cer | Discrepancy Analysis | error discription | docx source |
|---|---|---|---|---|---|---|
| 1 | 1. LCM (36, 45) = 2² × 3² × 5 = 180 Sec = 3 min 36 = 2² x 3² 45 = 3² x 5 Ans. : (3) 3 | 1. LCM (36,45) = 2² x 3² x 5 = 180 sec = 3min 36 = 2²x3² 45 = 3²x5 (3) 3 |  |  |  |  | 