| Discrepancy Type | Count of rows | Percentage of Total Entries (Rounded) |
|------------------|---------------|---------------------------------------|
| Spelling | 7 | 6.36% |
| Punctuation | 13 | 11.82% |
| Wording | 13 | 11.82% |
| Numerical Difference | 8 | 7.27% |
| NO ERRORS | 0 | 0.0% |
| Content Mix-up | 0 | 0.0% |
| Missing Content | 5 | 4.55% |
| Extra Content | 4 | 3.64% |
| Capitalization | 0 | 0.0% |
| Omission | 3 | 2.73% |
