| Discrepancy Type | Count of rows | Percentage of Total Entries (Rounded) |
|------------------|---------------|---------------------------------------|
| Spelling | 21 | 30.43% |
| Punctuation | 3 | 4.35% |
| Wording | 16 | 23.19% |
| Numerical Difference | 2 | 2.9% |
| NO ERRORS | 19 | 27.54% |
| Content Mix-up | 8 | 11.59% |
| Missing Content | 7 | 10.14% |
| Extra Content | 10 | 14.49% |
| Capitalization | 1 | 1.45% |
| Omission | 3 | 4.35% |
